name: Continuous Deployment
on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Deploy Staging
      if: github.ref == 'refs/heads/develop'
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.pxcx.com.br/wowconomy-dev
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-idr: ./build/

    - name: Deploy Production
      if: github.ref == 'refs/heads/master'
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.pxcx.com.br/wowconomy
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build